[project]
name = "mcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.14",
    "langchain-aws>=0.2.23",
    "langchain-mcp-adapters>=0.0.11",
    "langgraph>=0.4.3",
    "streamlit>=1.45.1",
]
