[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.3.1",
    "httpx>=0.28.1",
    "logging>=0.4.9.6",
    "mcp[cli]>=1.8.0",
]
